### ISSUE TITLE
NullReferenceException on a new client creation. 

### ISSUE THREAD

**Issue by iliuhin** [andreluizsecco/Cognitive-LUIS-Programmatic#2]
Hi, 

I have a problem when trying to access the appID of my LUIS app.
I double checked the subscription key and the location is set to WestEurope.

What can be the problem for the error below? Do i have to do any additional configuration before creating an LuisProgClient() object? 
 
![capture](https://user-images.githubusercontent.com/20401983/38038588-97016558-32ab-11e8-946a-f2a0ccb1de66.PNG)

**Comment by andreluizsecco** [comment]
Hello @iliuhin, this error occour when connection with your subscription fails. Please, check if your location is really WestEurope. For testing, try changing it to WestUS. For example:
```csharp
var client = new LuisProgClient(SUBSCRIPTION_KEY, Location.WestUS);
var app = client.GetAppByNameAsync("SDKTest").Result;
```

**Comment by iliuhin** [comment]
Hi @andreluizsecco, 
I did change the location to WestUS and the problem still remained. (But I'm pretty sure my app is registered in WestEurope).

But i noticed something else, i think there is a problem with the _baseUrl variable:
![url](https://user-images.githubusercontent.com/20401983/38076621-73e74c6e-3336-11e8-94c3-d6eb55b894a8.PNG)

In your case the url is:
[https://westeurope.api.cognitive.microsoft.com/luis/api/v2.0](url)

But if to look at Microsoft Documentation the url is the following:
[https://westeurope.api.cognitive.microsoft.com/luis/api/v2.0/apps](url)

![thenewlink](https://user-images.githubusercontent.com/20401983/38076674-9b68b8cc-3336-11e8-9019-186b2ded0841.PNG)

[https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c2f](url)

**Comment by andreluizsecco** [comment]
The _baseUrl of the SDK is correct. It will receive the "/apps" only when accessing the features related to apps, which can be seen, for example, in this line of source code:  [https://github.com/andreluizsecco/Cognitive-LUIS-Programmatic/blob/3e4231665a42661ea9f45af2ad0a0dc374fe9f6c/Cognitive.LUIS.Programmatic/LuisProgClient.cs#L22](url)

I'll need more information to find out the cause.
Could you get a print of the entire screen on the "publish" tab of your app? Delete the keys from the image.
Ex:

![image](https://user-images.githubusercontent.com/7199850/38121801-cca70c56-33a7-11e8-9dfb-b6b10ab9c24f.png)

If you prefer, send me an email (contato@andresecco.com.br) with your subscription key for my testing.

**Comment by iliuhin** [comment]
@andreluizsecco Thanks a lot for help, for some reason it worked without a problem when i used my Starter_Key. 
I find it pretty strange that the other keys that I've generated don't work... 

![luisapp](https://user-images.githubusercontent.com/20401983/38132071-c7a8fd7e-3409-11e8-99e8-15bfa40a0af5.PNG)

Btw, is there a way to retrieve/delete/edit the labeled utterances using Cognitive-LUIS-Programmatic?

**Comment by andreluizsecco** [comment]
I can not reproduce your problem here.

If you can contact me at contato@andresecco.com.br to test with your subscription key.

These features (retrieve/delete/edit the labeled utterances) are planned for version 1.1 (See the roadmap here : https://github.com/andreluizsecco/Cognitive-LUIS-Programmatic/wiki/roadmap)

**Comment by iliuhin** [comment]
To close the issue: 

LUIS can use two type of keys: **Authoring Key** and **Endpoint Key**. 
1. So basically the Authoring Key (called also Starter_Key) can be used with authoring Microsoft APIs, such as LUIS Programmatic APIs v2.0. 
2. But when the Endpoint Key (the one generated using Azure), is used with authoring APIs, then the error: "401 error - access denied due to invalid subscription key" is thrown (or in this case, a null object). The Endpoint key is used only when you deal with production endpoint queries.


Link: [https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-concept-keys](url)

@andreluizsecco Once again, thank you for help. Waiting for upcoming releases.

**Comment by gbertoncelli** [comment]
Same problem here, the solution was very useful, thanks!
