### ISSUE TITLE
Feature: Support versions endpoint

### ISSUE THREAD

**Issue by ghost** [andreluizsecco/Cognitive-LUIS-Programmatic#20]
Dear @andreluizsecco,
I want to let you know I'm working on supporting the /apps/{appId}/versions endpoint.

This is needed to cover my use case:
My use case is, to export the whole app (/apps/{appId}/versions/{versionId}/export) to json and then import it again on another luis instance (used for DevOps / CI/CD).

I'm working on it here:
https://github.com/michel-weber/Cognitive-LUIS-Programmatic/tree/feature/versionservice

I'm also implementing/extending your integration tests to cover my new code and trying to stay close to your naming/coding conventions.

Please let me know if you have any guidance on contributing to your project.

Kind regards
Michel

**Comment by andreluizsecco** [comment]
Hello Michel! Very good, the idea here is build a SDK from community to community. I took a brief look at your work and it seems all right. I hope your PR, thank you for contributing.

**Comment by ghost** [comment]
PR is #21 Cheers
