### ISSUE TITLE
Luis price Tier s0

### ISSUE THREAD

**Issue by gvizza83** [andreluizsecco/Cognitive-LUIS-Programmatic#29]
Hello Andre, it's possible to use Cognitive-Luis_Programmatic with a cognitive service Luis with Tier price S0 using di subscription key?

Thanks

**Comment by andreluizsecco** [comment]
Hello, Yes it's possible to use in the S0 tier, but the key that you should use in Cognitive.LUIS.Programmatic is the Authoring Key, read more here: https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-concept-keys

**Comment by gvizza83** [comment]
Yes, I have already read all the existing documentation. But if the key to use is the Authoring Key, where do I have to insert the "subscription key" or "Endpoint Key" in Cognitive.Luis.Programmatic to connect to a "Luis cognitive service" with tier price S0? can you give me an example?

**Comment by andreluizsecco** [comment]
So maybe you're confusing a bit. This SDK (Cognitive.LUIS.Programmatic) serves to automate tasks that you would do directly in the luis.ai portal, for example: creating intentions, entities, adding new examples, training and publishing your model. In practice, this SDK exists for you to be able to configure, maintain, and improve your model's learning without having to do this manually in the luis.ai portal.

This package (Cognitive.LUIS.Programmatic) only uses the Authoring Key and the usage example can be seen here: https://github.com/andreluizsecco/Cognitive-LUIS-Programmatic/wiki/get-started

I believe you are wanting to make use of the LUIS service (where you send a utterance and it returns the intentions and corresponding entities). This usage is done through an official Microsoft package (in this case for .NET): Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime. It is in this Microsoft package that you will use the Endpoint key.
You can find more about it in the official documentation: https://docs.microsoft.com/en-us/azure/cognitive-services/luis/sdk-csharp-quickstart-query-prediction-endpoint

**Comment by gvizza83** [comment]
Thanks for the answer, I created an app, which automatically from an excel file with intents and utterance configures a luis App in Luis portal, using cognitive.luis.programmatic. but if I do more than 5 operations per second I have Error 429 (Rate limit is exceeded (requests/second)). I thought that using an endpoint key with the tier price S0, I could solve the problem.

**Comment by andreluizsecco** [comment]
Oh right, now your doubt has become clearer.
This limit actually exists and is a limit imposed by the APIs provided by Microsoft.
You can make up to 5 requests per second for programmatic APIs, regardless of the price tier your LUIS service is on.
We are working on an enhancement here of this SDK so that we have a Retry feature, but that will be for the next version that will be out soon.

At this time, I recommend put your requests in a queue and implementing it so that your requests do not exceed 5 calls per second.
Unfortunately it is an API limitation, we do not have much to do about it.

**Comment by gvizza83** [comment]
Thank you for your answer, everything is clearer now.
