### ISSUE TITLE
[Question] Retrieving an Intent

### ISSUE THREAD

**Issue by gbertoncelli** [andreluizsecco/Cognitive-LUIS-Programmatic#3]
Hi,
I wanted to ask: if I use an Intent getter like `GetIntentByNameAsync(...) ` and the intent selected does not exists the method returns null? Or it tries to create a new Intent and returns that?

Thanks

**Comment by premaarya** [comment]
It will return null if the Intent doesn't exist. This method Queries the list of existing Intents in the LUIS application.

**Comment by gbertoncelli** [comment]
Perfect thanks!
