### ISSUE TITLE
[Question] Force training and publish

### ISSUE THREAD

**Issue by gbertoncelli** [andreluizsecco/Cognitive-LUIS-Programmatic#4]
Hi,
Is there a way to force the training in the moment I call the `TrainAsync(...)` method without queuing it? Or to wait until the training is finished successfully? And the same thing with publishing the model?
I would like to be sure that when I start these activities at a certain time they will be completed.
Thanks

**Comment by premaarya** [comment]
Hello,
The API is not available for force training or publish ..you can request the feature [here](https://cognitive.uservoice.com/forums/551524-language-understanding-luis). 
To determine whether the training request is successful, we will be  adding a get training status method soon OR better would be TrainAsync will return with the final status, the method will return when the Training is completed with status.

**Comment by gbertoncelli** [comment]
Thanks. 
So right now there is no way to know the status of a training or publishing activity that I've just sent?

**Comment by andreluizsecco** [comment]
@HighSoftWare96 The API currently provides a resource for send training/publishing request and another resource for get training/publishing status.
The request will queued, it takes a certain amount of time to be processed by LUIS (a few seconds), so you must make the request using this example: https://github.com/andreluizsecco/Cognitive-LUIS-Programmatic/wiki/get-started#sends-a-training-request, and if it has not yet been finalized, you need to check the status using that other method: https://github.com/andreluizsecco/Cognitive-LUIS-Programmatic/wiki/get-started#gets-the-training-status-of-all-models-intents-and-entities.
I will add to the backlog and open an issue to work on a solution that facilitates this process.

**Comment by andreluizsecco** [comment]
The issue #7 was created for tracking the request status.
