### ISSUE TITLE
does GetAllEntitiesAsync work?

### ISSUE THREAD

**Issue by gbertoncelli** [andreluizsecco/Cognitive-LUIS-Programmatic#9]
I'm trying to use GetAllEntitiesAsync (luisId, luisVersion) but it does not work in my case:
 IReadOnlyCollection<Entity> entities = await luisClient.GetAllEntitiesAsync(_config.LuisId, _config.LuisVersion);
returns always a collection with 0 items... Why is that? I've checked and for instance with GetAllIntentsAsync the _config.LuisId and _config.LuisVersion work.

**Comment by andreluizsecco** [comment]
Are you sure you have entities added to your LUIS app?

**Comment by gbertoncelli** [comment]
Pretty sure... But for example in the LuIs web portal I cannot find out the IDs of the entity (is that normal?).. In the project I needed the names of the entities but I've solved the situation saving the names in a database.

**Comment by andreluizsecco** [comment]
Could you post a print from your LUIS portal entities screen?

**Comment by andreluizsecco** [comment]
Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.
